// TODO: Keep additional network capabilities inside Schema and Protocol as the client grows; /effect must never import
// Core or Server. Preserve these datatype exports so internal model reorganizations do not require caller migrations.
export * from "./generated-effect/index"
export { Agent } from "@spacecode/schema/agent"
export { Command } from "@spacecode/schema/command"
export { Credential } from "@spacecode/schema/credential"
export { FileSystem } from "@spacecode/schema/filesystem"
export { Integration } from "@spacecode/schema/integration"
export { Location } from "@spacecode/schema/location"
export { Model } from "@spacecode/schema/model"
export { Permission } from "@spacecode/schema/permission"
export { PermissionSaved } from "@spacecode/schema/permission-saved"
export { Project } from "@spacecode/schema/project"
export { ProjectCopy } from "@spacecode/schema/project-copy"
export { Provider } from "@spacecode/schema/provider"
export { Pty } from "@spacecode/schema/pty"
export { Question } from "@spacecode/schema/question"
export { Reference } from "@spacecode/schema/reference"
export { AbsolutePath, RelativePath } from "@spacecode/schema/schema"
export { Session } from "@spacecode/schema/session"
export { SessionInput } from "@spacecode/schema/session-input"
export { SessionMessage } from "@spacecode/schema/session-message"
export { Skill } from "@spacecode/schema/skill"
export { Prompt } from "@spacecode/schema/prompt"
export type { SpaceCodeEvent } from "@spacecode/protocol/groups/event"
